### ISSUE TITLE
Editor errors are ignored

### ISSUE THREAD

**Issue by sander2** [szabta89/IncA#12] opened 2018-02-05 20:33 UTC
When there are errors in a pattern function module, IncA should refuse to compile, but the current behavior is that it will happily compile and run the analysis.

**Comment by szabta89** [comment] 2018-02-11 20:20
@sander2 I have added a new functionality in the form of a compiler option. I decided for an opt-in solution, i.e. you need to enable the strict mode explicitly in the compiler options. See the screenshot below:
<img width="645" alt="screen shot 2018-02-11 at 21 18 58" src="https://user-images.githubusercontent.com/1330202/36077972-59c9a13a-0f71-11e8-9876-9979cd0b0eb1.png">

**Comment by sander2** [comment] 2018-02-11 20:51
Alright. 48a9a13 doesn't seem to work for me though; I enabled strict mode, yet it compiles without error.

**Comment by szabta89** [comment] 2018-02-11 20:53
First of all, the stuff is causing a build failure which needs to be debugged. Some classes are not available at runtime. Second, it is pretty hard for me to say anything in response to a sentence like yours. How can I reproduce the issue?

**Comment by szabta89** [comment] 2018-02-11 20:53
I reverted the commit on master, and I created the feature/12 branch.

**Comment by sander2** [comment] 2018-02-11 21:14
Hmm strange, compiling IncA with that commit didn't produce any errors for me. Anyway, all I did for my test was to introduce a typing error in my analysis code and trying compile it. I can push some code if you can't easily reproduce it.

**Comment by szabta89** [comment] 2018-02-11 21:27
The compilation failure can only be witnessed on the server, you cant reproduce that locally.

**Comment by szabta89** [comment] 2018-02-11 21:29
This is what I see when I intentionally make a mistake in your code. 
<img width="1670" alt="screen shot 2018-02-11 at 22 28 35" src="https://user-images.githubusercontent.com/1330202/36078735-f7553a50-0f7a-11e8-8e85-7a84f5639253.png">

**Comment by szabta89** [comment] 2018-06-15 14:30
After many tries, I must say that there is no way currently to support this issue. The modelchecker will have a different packaging in MPS 2018.2, maybe then it will be possible to make the build work.

**Comment by szabta89** [comment] 2018-09-02 12:57
This issue has been fixed with MPS 2018.2.

**Closed as completed by szabta89** 2018-09-02 12:57 UTC
